//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonsal_Gardent.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentProduct
    {
        public int ID { get; set; }
        public string Content { get; set; }
        public Nullable<int> ProductID { get; set; }
        public int AccCustomerID { get; set; }
    
        public virtual AccCustomer AccCustomer { get; set; }
        public virtual AccCustomer AccCustomer1 { get; set; }
        public virtual Product Product { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
