//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonsal_Gardent.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int ID { get; set; }
        public int CustomerOrderID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Note { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual CustomerOrder CustomerOrder { get; set; }
        public virtual CustomerOrder CustomerOrder1 { get; set; }
        public virtual Product Product { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual StatusOrder StatusOrder { get; set; }
        public virtual StatusOrder StatusOrder1 { get; set; }
    }
}
