//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonsal_Gardent.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public string Path { get; set; }
        public Nullable<int> TypeID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
